name: Node.js CI/CD on Amazon Linux

on:
  pull_request:
    branches:
      - main
    types:
      - closed  # Trigger the workflow when a pull request is closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true  # Ensure the job only runs if the pull request was merged
    runs-on: ubuntu-latest  # The job will run on the latest version of Ubuntu

    steps:
    - uses: actions/checkout@v2  # Checkout the repository's code

    - name: Install dependencies
      run: npm install  # Install Node.js dependencies

    - name: Deploy to AWS EC2
      uses: appleboy/scp-action@master  # Use scp-action to copy files to the EC2 instance
      with:
        host: ${{ secrets.REMOTE_IP }}  # Hostname or IP address of the EC2 instance
        username: ${{ secrets.REMOTE_USER }}  # SSH username for the EC2 instance
        key: ${{ secrets.REMOTE_KEY }}  # SSH private key for authentication
        source: "./"  # Source directory to copy (current directory of the project)
        target: "/app"  # Target directory on the EC2 instance

    - name: Restart PM2 application
      uses: appleboy/ssh-action@master  # Use ssh-action to execute commands on the EC2 instance
      with:
        host: ${{ secrets.REMOTE_HOST }}  # Hostname or IP address of the EC2 instance
        username: ${{ secrets.REMOTE_USER }}  # SSH username for the EC2 instance
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key for authentication
        script: |
          cd app  # Change to the project directory
          pm2 reload all  # Restart all PM2 managed applications
